### ISSUE TITLE
Update both Web projects to use Bootstrap 5

### ISSUE THREAD

**Issue by madison-boman** [MCLD/ocuda#344]
Information can be found on the Bootstrap [Migrating to v5](https://getbootstrap.com/docs/5.0/migration/) page.

- [x] After updating to Bootstrap v5.0, the style classes `fs-5` and `fs-6` must be removed from `styles.css`

**Comment by k7hpn** [comment]
Branch [`feature/bootstrap5`](https://github.com/MCLD/ocuda/tree/feature/bootstrap5) created for this effort.
